### ISSUE TITLE
Document code conventions

### ISSUE THREAD

**Issue by cb0s** [wuespace/telestion-docs#31]

**Comment by pklaschka** [comment]
I don't think that this is a part of this repo, as it is.

If there's something specific you want to have documented (e.g., naming patterns for Verticles), that's something that we could put in here. For that, please open more specific issues (using the issue forms in this repo) for your particular request.

As it is, I read this as documenting stuff like tabs vs. spaces, which, in my opinion, should be handled by a formatter/config files instead of a manual reference in our documentation.

I'm closing this for now. Please feel free to open more specific issues if you think it's necessary. Thanks 🙂
